apiVersion: batch/v1
kind: Job
metadata:
  name: k-kubectl-job-1
  namespace: kapp
  labels:
    app: k-kubectl
spec:
  template:
    spec:
      containers:
      - name: k-kubectl
        image: bitnami/kubectl:latest
        command: ["kubectl", "delete", "namespace", "abc"]
      restartPolicy: Never
  backoffLimit: 4