apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: kapp
spec:
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: host.docker.internal:5555/producer:latest
        imagePullPolicy: Always
        command: ["python", "producer.py"]
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
